export const STANDARD_LEDGER_CODES = {
  CASH: { label: 'Cash', category: 'cash_bank' },
  PETTY_CASH: { label: 'Petty Cash', category: 'cash_bank' },
  DEFAULT_BANK: { label: 'Default Bank', category: 'cash_bank' },
  CUSTOMERS: { label: 'Customers Control', category: 'party' },
  SUPPLIERS: { label: 'Suppliers Control', category: 'party' },
  SALES: { label: 'Sales', category: 'revenue' },
  SERVICE_CHARGE: { label: 'Service Income', category: 'revenue' },
  PURCHASES: { label: 'Purchases', category: 'purchases' },
  DISCOUNT_ALLOWED: { label: 'Discount Allowed', category: 'discounts' },
  DISCOUNT_RECEIVED: { label: 'Discount Received', category: 'discounts' },
  CAPITAL: { label: 'Capital', category: 'equity' },
  DRAWINGS: { label: 'Drawings', category: 'equity' },
  RETAINED_EARNINGS: { label: 'Retained Earnings', category: 'equity' },
  INPUT_VAT: { label: 'Input VAT', category: 'tax' },
  OUTPUT_VAT: { label: 'Output VAT', category: 'tax' },
  VAT_PAYABLE: { label: 'VAT Payable', category: 'tax' },
  VAT_RECEIVABLE: { label: 'VAT Receivable', category: 'tax' },
  TDS_PAYABLE: { label: 'TDS Payable', category: 'tax' },
  TDS_RECEIVABLE: { label: 'TDS Receivable', category: 'tax' },
  INPUT_TAX: { label: 'Input Tax', category: 'tax' },
  OUTPUT_TAX: { label: 'Output Tax', category: 'tax' },
  TAX_PAYABLE: { label: 'Tax Payable', category: 'tax' },
  TAX_RECEIVABLE: { label: 'Tax Receivable', category: 'tax' },
} as const;
